# OCI development settings. Image digests are promoted by GitHub Actions.
imageRegistry: docker.io/garyrizzo1992
image:
  tag: main
  digest: sha256:d4fb41c96fe1015ae85934e4df636b08160f8493ba236d6bd2c3f16c1f16bb1f
tracing:
  enabled: true
kafka:
  enabled: true
autoscaling:
  enabled: true
