# OCI development settings. Image digests are promoted by GitHub Actions.
imageRegistry: docker.io/garyrizzo1992
image:
  tag: main
  digest: sha256:8674d10e2adc5573f872c89c0b8f1219226d27efba736c078a3f5bfb465d1f3a
tracing:
  enabled: true
kafka:
  enabled: true
autoscaling:
  enabled: true
