# OCI development settings. Image digests are promoted by GitHub Actions.
imageRegistry: docker.io/garyrizzo1992
image:
  tag: main
  digest: sha256:a19bcbd036df0f57b271198532d52351093ff64885c1eb2e0eec748abe206c4e
tracing:
  enabled: true
kafka:
  enabled: true
autoscaling:
  enabled: true
  maxReplicas: 2
