# OCI development settings. Image digests are promoted by GitHub Actions.
imageRegistry: docker.io/garyrizzo1992
image:
  tag: main
  digest: sha256:fb1c934dea089620a31b8ccfe985098ab624417edc4aba571c7f798e6f3b8bb9
externalSecrets:
  enabled: true
  vaultId: ocid1.vault.oc1.eu-milan-1.hjvl5nnyaadq2.abwgsljrhqsvxa5k42ihwackhwkndppsmgeakyk2gzdi6j2i7d462npsxlmq
  secretName: dummy-exchange-dev-jwt-secret
tracing:
  enabled: true
trustCloudflare: true
