# OCI development settings. Image digests are promoted by GitHub Actions.
imageRegistry: docker.io/garyrizzo1992
image:
  tag: main
  digest: sha256:61d13a78f49570129976a7ca2bf92b1d0e9410660ffc7a8ccaf916bd78cca695
externalSecrets:
  enabled: true
  vaultId: ocid1.vault.oc1.eu-milan-1.hjvl5nnyaadq2.abwgsljrhqsvxa5k42ihwackhwkndppsmgeakyk2gzdi6j2i7d462npsxlmq
  secretName: dummy-exchange-dev-jwt-secret
tracing:
  enabled: true
trustCloudflare: true
