CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE TABLE users (id uuid PRIMARY KEY DEFAULT uuid_generate_v4(), email text UNIQUE NOT NULL, password_hash text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE accounts (id uuid PRIMARY KEY DEFAULT uuid_generate_v4(), user_id uuid NOT NULL REFERENCES users(id), currency text NOT NULL, available numeric(30,10) NOT NULL DEFAULT 0, reserved numeric(30,10) NOT NULL DEFAULT 0, UNIQUE(user_id,currency));
CREATE TABLE instruments (symbol text PRIMARY KEY, base_currency text NOT NULL, quote_currency text NOT NULL, tick_size numeric(30,10) NOT NULL, enabled boolean NOT NULL DEFAULT true);
CREATE TABLE orders (id uuid PRIMARY KEY DEFAULT uuid_generate_v4(), user_id uuid NOT NULL REFERENCES users(id), client_order_id text NOT NULL, instrument text NOT NULL REFERENCES instruments(symbol), side text NOT NULL CHECK(side IN ('buy','sell')), order_type text NOT NULL CHECK(order_type IN ('market','limit')), quantity numeric(30,10) NOT NULL, remaining numeric(30,10) NOT NULL, limit_price numeric(30,10), status text NOT NULL, sequence bigserial UNIQUE, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(user_id,client_order_id));
CREATE TABLE fills (id uuid PRIMARY KEY DEFAULT uuid_generate_v4(), maker_order_id uuid NOT NULL REFERENCES orders(id), taker_order_id uuid NOT NULL REFERENCES orders(id), instrument text NOT NULL, price numeric(30,10) NOT NULL, quantity numeric(30,10) NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(maker_order_id,taker_order_id,price,quantity));
CREATE TABLE outbox_events (id uuid PRIMARY KEY DEFAULT uuid_generate_v4(), kind text NOT NULL, aggregate_id uuid NOT NULL, payload jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), processed_at timestamptz);
CREATE TABLE audit_log (id bigserial PRIMARY KEY, actor_id uuid, action text NOT NULL, entity_id uuid, metadata jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX orders_book_idx ON orders(instrument, status, side, limit_price, sequence);
