apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dummy-exchange-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: dummy-exchange
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    retry:
      limit: 5
      refresh: true
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
  sources:
  - repoURL: https://github.com/garyrizzo1992/dummy_exchange.git
    targetRevision: main
    path: deploy/helm/exchange-api
    helm:
      releaseName: dummy-exchange-dev
      valueFiles:
      - values.yaml
      - values-dev.yaml
  - repoURL: https://github.com/garyrizzo1992/dummy_exchange.git
    targetRevision: main
    path: deploy/helm/exchange-worker
    helm:
      releaseName: dummy-exchange-dev
      valueFiles:
      - values.yaml
      - values-dev.yaml
  - repoURL: https://github.com/garyrizzo1992/dummy_exchange.git
    targetRevision: main
    path: deploy/helm/exchange
    helm:
      releaseName: dummy-exchange-dev
      valueFiles:
      - values.yaml
      - values-dev.yaml
