[package]
name = "exchange-simulator"
version.workspace = true
edition.workspace = true

[dependencies]
exchange-config = { path = "../config" }
anyhow.workspace = true
axum.workspace = true
chrono.workspace = true
dotenvy.workspace = true
metrics.workspace = true
metrics-exporter-prometheus.workspace = true
rand.workspace = true
rust_decimal.workspace = true
serde_json.workspace = true
sqlx.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true
exchange-trading = { path = "../trading" }
exchange-domain = { path = "../domain" }
