{{- if .Values.enabled }}
{{- $name := include "exchange-monitoring.fullname" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $name }}-grafana-provisioning
  labels:
    {{- include "exchange-monitoring.labels" . | nindent 4 }}
data:
  prometheus.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        uid: prometheus
        type: prometheus
        access: proxy
        url: http://{{ $name }}-prometheus:9090
        isDefault: true
        editable: false
      {{- if .Values.logging.enabled }}
      - name: Loki
        uid: loki
        type: loki
        access: proxy
        url: http://{{ $name }}-loki:3100
        editable: false
        jsonData:
          maxLines: 1000
          {{- if .Values.tracing.enabled }}
          derivedFields:
            - name: TraceID
              matcherRegex: '"trace_id"\s*:\s*"([0-9a-f]{32})"'
              datasourceUid: tempo
              url: '$${__value.raw}'
              urlDisplayLabel: View trace
          {{- end }}
      {{- end }}
      {{- if .Values.tracing.enabled }}
      - name: Tempo
        uid: tempo
        type: tempo
        access: proxy
        url: http://{{ $name }}-tempo:3200
        editable: false
        jsonData:
          tracesToLogsV2:
            datasourceUid: loki
            tags:
              - {key: service.name, value: service}
            spanStartTimeShift: '-1m'
            spanEndTimeShift: '1m'
            filterByTraceID: false
            customQuery: true
            query: '{namespace="dummy-exchange"} |= "$${__trace.traceId}"'
          tracesToMetrics:
            datasourceUid: prometheus
      {{- end }}
  dashboards.yaml: |
    apiVersion: 1
    providers:
      - name: Exchange
        orgId: 1
        folder: Exchange
        type: file
        disableDeletion: true
        editable: false
        options:
          path: /var/lib/grafana/dashboards
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $name }}-grafana-dashboard
  labels:
    {{- include "exchange-monitoring.labels" . | nindent 4 }}
data:
  exchange-scaling.json: |
    {{- .Files.Get "files/exchange-scaling.json" | nindent 4 }}
  {{- if .Values.tracing.enabled }}
  exchange-tracing.json: |
    {{- .Files.Get "files/exchange-tracing.json" | nindent 4 }}
  {{- end }}
  exchange-overview.json: |
    {{- .Files.Get "files/exchange-overview.json" | nindent 4 }}
  {{- if .Values.kubernetes.enabled }}
  kubernetes-overview.json: |
    {{- .Files.Get "files/kubernetes-overview.json" | nindent 4 }}
  {{- end }}
  {{- if .Values.logging.enabled }}
  kubernetes-logs.json: |
    {{- .Files.Get "files/kubernetes-logs.json" | nindent 4 }}
  {{- end }}
{{- end }}
