{{- if .Values.enabled }}
{{- $name := include "exchange-monitoring.fullname" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $name }}-grafana-provisioning
  labels:
    {{- include "exchange-monitoring.labels" . | nindent 4 }}
data:
  prometheus.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        uid: prometheus
        type: prometheus
        access: proxy
        url: http://{{ $name }}-prometheus:9090
        isDefault: true
        editable: false
      {{- if .Values.logging.enabled }}
      - name: Loki
        uid: loki
        type: loki
        access: proxy
        url: http://{{ $name }}-loki:3100
        editable: false
        jsonData:
          maxLines: 1000
      {{- end }}
  dashboards.yaml: |
    apiVersion: 1
    providers:
      - name: Exchange
        orgId: 1
        folder: Exchange
        type: file
        disableDeletion: true
        editable: false
        options:
          path: /var/lib/grafana/dashboards
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $name }}-grafana-dashboard
  labels:
    {{- include "exchange-monitoring.labels" . | nindent 4 }}
data:
  exchange-overview.json: |
    {{- .Files.Get "files/exchange-overview.json" | nindent 4 }}
  {{- if .Values.kubernetes.enabled }}
  kubernetes-overview.json: |
    {{- .Files.Get "files/kubernetes-overview.json" | nindent 4 }}
  {{- end }}
  {{- if .Values.logging.enabled }}
  kubernetes-logs.json: |
    {{- .Files.Get "files/kubernetes-logs.json" | nindent 4 }}
  {{- end }}
{{- end }}
