{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ include "exchange-monitoring.fullname" . }}-monitoring-vault
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
spec:
  provider:
    oracle:
      vault: {{ required "externalSecrets.vaultId is required" .Values.externalSecrets.vaultId | quote }}
      region: {{ .Values.externalSecrets.region | quote }}
      principalType: InstancePrincipal
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "exchange-monitoring.fullname" . }}-monitoring-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: {{ include "exchange-monitoring.fullname" . }}-monitoring-vault
  target:
    name: {{ .Values.grafana.adminSecret.name }}
    creationPolicy: Owner
  data:
    - secretKey: {{ .Values.grafana.adminSecret.key }}
      remoteRef:
        key: {{ required "externalSecrets.secretName is required" .Values.externalSecrets.secretName | quote }}
{{- end }}
